/*
 * Admin can ADD a product to the store along with all the details
 */
package projectshopping;

import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;
import javax.swing.JFileChooser;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;

public class AddStock extends javax.swing.JPanel {

    private Connection conn;

    /**
     * Creates new form AddStock
     */
    public AddStock() {
        initComponents();
        this.setSize(1920, 1080);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jFileChooser2 = new javax.swing.JFileChooser();
        jFileChooser3 = new javax.swing.JFileChooser();
        jScrollBar1 = new javax.swing.JScrollBar();
        jLabel1 = new javax.swing.JLabel();
        productName = new javax.swing.JLabel();
        price = new javax.swing.JLabel();
        image = new javax.swing.JLabel();
        stock = new javax.swing.JLabel();
        brand = new javax.swing.JLabel();
        type = new javax.swing.JLabel();
        subType = new javax.swing.JLabel();
        colour = new javax.swing.JLabel();
        description = new javax.swing.JLabel();
        length = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        cost = new javax.swing.JTextField();
        imageField = new javax.swing.JTextField();
        choosePhoto = new javax.swing.JButton();
        stockField = new javax.swing.JTextField();
        brandField = new javax.swing.JTextField();
        typeField = new javax.swing.JTextField();
        subTypeField = new javax.swing.JTextField();
        colourField = new javax.swing.JTextField();
        size = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        descArea = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        ratings = new javax.swing.JLabel();
        rateField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        jFileChooser3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFileChooser3ActionPerformed(evt);
            }
        });

        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/add product panel.PNG"))); // NOI18N
        add(jLabel1);
        jLabel1.setBounds(80, 0, 860, 90);

        productName.setFont(new java.awt.Font("Stencil Std", 1, 36)); // NOI18N
        productName.setText("Product Name :");
        productName.setToolTipText("");
        add(productName);
        productName.setBounds(40, 160, 330, 28);

        price.setFont(new java.awt.Font("Stencil Std", 1, 36)); // NOI18N
        price.setText("Price :");
        add(price);
        price.setBounds(40, 220, 264, 29);

        image.setFont(new java.awt.Font("Stencil Std", 1, 36)); // NOI18N
        image.setText("Insert Image :");
        add(image);
        image.setBounds(40, 270, 320, 37);

        stock.setFont(new java.awt.Font("Stencil Std", 1, 36)); // NOI18N
        stock.setText("Stock :");
        add(stock);
        stock.setBounds(40, 330, 264, 40);

        brand.setFont(new java.awt.Font("Stencil Std", 1, 36)); // NOI18N
        brand.setText("Brand Name :");
        add(brand);
        brand.setBounds(40, 400, 300, 26);

        type.setFont(new java.awt.Font("Stencil Std", 1, 36)); // NOI18N
        type.setText("Type :");
        add(type);
        type.setBounds(40, 460, 264, 30);

        subType.setFont(new java.awt.Font("Stencil Std", 1, 36)); // NOI18N
        subType.setText("Sub-Type :");
        add(subType);
        subType.setBounds(40, 520, 264, 40);

        colour.setFont(new java.awt.Font("Stencil Std", 1, 36)); // NOI18N
        colour.setText("Colour :");
        add(colour);
        colour.setBounds(40, 590, 264, 34);

        description.setFont(new java.awt.Font("Stencil Std", 1, 36)); // NOI18N
        description.setText("Description :");
        add(description);
        description.setBounds(40, 770, 300, 50);

        length.setFont(new java.awt.Font("Stencil Std", 1, 36)); // NOI18N
        length.setText("Size:");
        add(length);
        length.setBounds(40, 710, 264, 40);

        name.setFont(new java.awt.Font("Stencil Std", 1, 24)); // NOI18N
        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });
        add(name);
        name.setBounds(510, 150, 502, 40);

        cost.setFont(new java.awt.Font("Stencil Std", 1, 24)); // NOI18N
        add(cost);
        cost.setBounds(510, 210, 502, 40);

        imageField.setFont(new java.awt.Font("Stencil Std", 1, 24)); // NOI18N
        add(imageField);
        imageField.setBounds(510, 270, 360, 50);

        choosePhoto.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        choosePhoto.setText("Choose File");
        choosePhoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                choosePhotoActionPerformed(evt);
            }
        });
        add(choosePhoto);
        choosePhoto.setBounds(880, 270, 140, 50);

        stockField.setFont(new java.awt.Font("Stencil Std", 1, 24)); // NOI18N
        stockField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stockFieldActionPerformed(evt);
            }
        });
        add(stockField);
        stockField.setBounds(510, 330, 410, 50);

        brandField.setFont(new java.awt.Font("Stencil Std", 1, 24)); // NOI18N
        brandField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brandFieldActionPerformed(evt);
            }
        });
        add(brandField);
        brandField.setBounds(510, 400, 502, 40);

        typeField.setFont(new java.awt.Font("Stencil Std", 1, 24)); // NOI18N
        add(typeField);
        typeField.setBounds(510, 460, 502, 40);

        subTypeField.setFont(new java.awt.Font("Stencil Std", 1, 24)); // NOI18N
        add(subTypeField);
        subTypeField.setBounds(510, 522, 502, 40);

        colourField.setFont(new java.awt.Font("Stencil Std", 1, 24)); // NOI18N
        add(colourField);
        colourField.setBounds(510, 582, 502, 40);

        size.setFont(new java.awt.Font("Stencil Std", 1, 24)); // NOI18N
        add(size);
        size.setBounds(510, 702, 502, 40);

        descArea.setColumns(20);
        descArea.setFont(new java.awt.Font("Stencil Std", 1, 24)); // NOI18N
        descArea.setRows(5);
        jScrollPane1.setViewportView(descArea);

        add(jScrollPane1);
        jScrollPane1.setBounds(510, 760, 502, 131);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/add button.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2);
        jButton2.setBounds(290, 880, 210, 110);

        ratings.setFont(new java.awt.Font("Stencil Std", 1, 36)); // NOI18N
        ratings.setText("Ratings :");
        add(ratings);
        ratings.setBounds(40, 650, 264, 32);

        rateField.setFont(new java.awt.Font("Stencil Std", 1, 24)); // NOI18N
        add(rateField);
        rateField.setBounds(510, 642, 502, 40);
        add(jLabel2);
        jLabel2.setBounds(36, 13, 0, 0);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectshopping/cart.jpg"))); // NOI18N
        add(jLabel3);
        jLabel3.setBounds(10, 0, 1920, 1010);
    }// </editor-fold>//GEN-END:initComponents

    private void jFileChooser3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFileChooser3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFileChooser3ActionPerformed

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    private void choosePhotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_choosePhotoActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Select Photo");
        int returnValue = fileChooser.showOpenDialog(this);
        if(returnValue == fileChooser.APPROVE_OPTION) {
            File photoFile = fileChooser.getSelectedFile();
            imageField.setText(photoFile.getPath());
        }
    }//GEN-LAST:event_choosePhotoActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try {
        File imgfile = new File(imageField.getText());
        FileInputStream fis = new FileInputStream(imgfile);
        
            Class.forName("com.mysql.jdbc.Driver");
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/fashion_store_db", "root", "");
            
            PreparedStatement pre = conn.prepareStatement("INSERT INTO cloth VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, CURDATE())");
            pre.setInt(1, 1235);
            pre.setString(2, name.getText());
            pre.setInt(3, Integer.parseInt(cost.getText()));
            pre.setInt(4, Integer.parseInt(stockField.getText()));
            pre.setString(5, brandField.getText());
            pre.setString(6, typeField.getText());
            pre.setString(7, subTypeField.getText());
            pre.setString(8, colourField.getText());
            pre.setInt(9, Integer.parseInt(rateField.getText()));                
            pre.setString(11, size.getText());
            pre.setString(10, descArea.getText());  
            pre.setBinaryStream(12, fis, fis.available());
            pre.executeUpdate();
            pre.close();          
            conn.close();
        } catch (IOException | ClassNotFoundException | NumberFormatException | SQLException ex) {
            System.out.println(ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void stockFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stockFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stockFieldActionPerformed

    private void brandFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brandFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_brandFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel brand;
    private javax.swing.JTextField brandField;
    private javax.swing.JButton choosePhoto;
    private javax.swing.JLabel colour;
    private javax.swing.JTextField colourField;
    private javax.swing.JTextField cost;
    private javax.swing.JTextArea descArea;
    private javax.swing.JLabel description;
    private javax.swing.JLabel image;
    private javax.swing.JTextField imageField;
    private javax.swing.JButton jButton2;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JFileChooser jFileChooser2;
    private javax.swing.JFileChooser jFileChooser3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel length;
    private javax.swing.JTextField name;
    private javax.swing.JLabel price;
    private javax.swing.JLabel productName;
    private javax.swing.JTextField rateField;
    private javax.swing.JLabel ratings;
    private javax.swing.JTextField size;
    private javax.swing.JLabel stock;
    private javax.swing.JTextField stockField;
    private javax.swing.JLabel subType;
    private javax.swing.JTextField subTypeField;
    private javax.swing.JLabel type;
    private javax.swing.JTextField typeField;
    // End of variables declaration//GEN-END:variables
}
