/*
 * This is the FIRST PAGE of the project
 * The project starts from this .java file
 * This file contains the name of the online fashioin store
 */
package projectshopping;

import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;


public class LoadScreen extends javax.swing.JFrame implements ActionListener,ChangeListener{
    int x =0;
    int min = 0;
    int max = 10;
    int y = x;
    Timer tm;
    /**
     * Creates new form LoadScreen
     */
    public LoadScreen() {
        initComponents();
        setSize(1920, 1080);
        this.getContentPane().setBackground(Color.WHITE);
         this.setTitle("MAD Creationzzz!!!");
        
        Image icon = Toolkit.getDefaultToolkit().getImage("src/img/i1.jpg");
        this.setIconImage(icon);
        
         jProgressBar2.setMaximum(max);
        jProgressBar2.setMinimum(min);
        jProgressBar2.setStringPainted(true);
        jProgressBar2.addChangeListener(this);
        
         tm = new Timer(3000,new ActionListener()
            
        {       @Override
    public void actionPerformed(ActionEvent e) {
       
      
       while(x<=100){
           jProgressBar2.setValue(x);
            x +=1;
       }
       
       x = 100;
    }  
        });
         
         tm.start();
         y = x;
        
        
        
    }

    
           
       
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jProgressBar2 = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/HomeScreen1.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1930, 890);

        jProgressBar2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jProgressBar2MouseEntered(evt);
            }
        });
        getContentPane().add(jProgressBar2);
        jProgressBar2.setBounds(710, 900, 540, 70);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jProgressBar2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jProgressBar2MouseEntered
        // TODO add your handling code here:
         HomePage h1 = new HomePage();
         h1.setVisible(true);
         this.setVisible(false);
    }//GEN-LAST:event_jProgressBar2MouseEntered

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoadScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoadScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoadScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoadScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoadScreen().setVisible(true);
            }
        });
    }

    
          
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JProgressBar jProgressBar2;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void stateChanged(ChangeEvent e) {
       // throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
