/*
 * This is the USER SIGN UP screen for registering a new user.
 */
package projectshopping;

import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;


public class UserSignUpScreen extends javax.swing.JFrame implements ItemListener{
        private Connection conn;
        String genderType;
        
        ButtonGroup gender = new ButtonGroup();
    /**
     * Creates new form UserSignUpScreen
     */
    public UserSignUpScreen() {
        initComponents();
        this.setSize(1920, 1080);
         this.setTitle("MAD Creationzzz!!!");
        Image icon = Toolkit.getDefaultToolkit().getImage("src/img/i1.jpg");
        this.setIconImage(icon);
        
        gender.add(maleButton);
        gender.add(femaleButton);
        
        maleButton.addItemListener(this);
        femaleButton.addItemListener(this);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        firstName = new javax.swing.JTextField();
        lastName = new javax.swing.JTextField();
        userName = new javax.swing.JTextField();
        password = new javax.swing.JTextField();
        age = new javax.swing.JTextField();
        image = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        phoneNumber = new javax.swing.JTextField();
        maleButton = new javax.swing.JRadioButton();
        femaleButton = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        city = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        pinCode = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        address = new javax.swing.JTextArea();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/sign up frame.PNG"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(690, 20, 680, 85);

        jLabel2.setFont(new java.awt.Font("Stencil Std", 1, 24)); // NOI18N
        jLabel2.setText("First Name:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(680, 120, 162, 41);

        jLabel3.setFont(new java.awt.Font("Stencil Std", 1, 24)); // NOI18N
        jLabel3.setText("Last Name:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(680, 170, 149, 30);

        jLabel4.setFont(new java.awt.Font("Stencil Std", 1, 24)); // NOI18N
        jLabel4.setText("User Name:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(680, 220, 155, 25);

        jLabel5.setFont(new java.awt.Font("Stencil Std", 1, 24)); // NOI18N
        jLabel5.setText("Password:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(680, 270, 150, 44);

        jLabel6.setFont(new java.awt.Font("Stencil Std", 1, 24)); // NOI18N
        jLabel6.setText("Age:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(680, 330, 80, 25);

        jLabel7.setFont(new java.awt.Font("Stencil Std", 1, 24)); // NOI18N
        jLabel7.setText("Gender:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(680, 370, 120, 39);

        jLabel8.setFont(new java.awt.Font("Stencil Std", 1, 24)); // NOI18N
        jLabel8.setText("Email:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(680, 420, 100, 47);

        jLabel12.setFont(new java.awt.Font("Stencil Std", 1, 24)); // NOI18N
        jLabel12.setText("Phone Number:");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(680, 800, 230, 30);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/sign up button.jpg"))); // NOI18N
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(890, 890, 209, 93);
        getContentPane().add(firstName);
        firstName.setBounds(1090, 120, 310, 40);
        getContentPane().add(lastName);
        lastName.setBounds(1090, 170, 310, 40);
        getContentPane().add(userName);
        userName.setBounds(1090, 220, 220, 37);
        getContentPane().add(password);
        password.setBounds(1090, 270, 221, 40);

        age.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ageActionPerformed(evt);
            }
        });
        getContentPane().add(age);
        age.setBounds(1090, 330, 91, 37);

        image.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imageActionPerformed(evt);
            }
        });
        getContentPane().add(image);
        image.setBounds(1090, 740, 340, 43);

        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });
        getContentPane().add(email);
        email.setBounds(1090, 430, 340, 40);

        phoneNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneNumberActionPerformed(evt);
            }
        });
        getContentPane().add(phoneNumber);
        phoneNumber.setBounds(1090, 800, 270, 41);

        maleButton.setFont(new java.awt.Font("Stencil Std", 1, 18)); // NOI18N
        maleButton.setText("male");
        maleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleButtonActionPerformed(evt);
            }
        });
        getContentPane().add(maleButton);
        maleButton.setBounds(1090, 390, 81, 27);

        femaleButton.setFont(new java.awt.Font("Stencil Std", 1, 18)); // NOI18N
        femaleButton.setText("female");
        getContentPane().add(femaleButton);
        femaleButton.setBounds(1190, 390, 110, 27);

        jLabel9.setFont(new java.awt.Font("Stencil Std", 1, 24)); // NOI18N
        jLabel9.setText("Your Photo:");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(680, 740, 180, 25);

        jButton2.setFont(new java.awt.Font("Stencil Std", 1, 18)); // NOI18N
        jButton2.setText("Choose File");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(1440, 737, 160, 50);

        jLabel10.setFont(new java.awt.Font("Stencil Std", 1, 24)); // NOI18N
        jLabel10.setText("Address:");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(680, 490, 130, 30);

        city.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cityActionPerformed(evt);
            }
        });
        getContentPane().add(city);
        city.setBounds(1090, 620, 270, 40);

        jLabel11.setFont(new java.awt.Font("Stencil Std", 1, 24)); // NOI18N
        jLabel11.setText("City:");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(680, 630, 160, 30);

        pinCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pinCodeActionPerformed(evt);
            }
        });
        getContentPane().add(pinCode);
        pinCode.setBounds(1090, 680, 190, 40);

        address.setColumns(20);
        address.setRows(5);
        jScrollPane1.setViewportView(address);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(1090, 486, 280, 110);

        jLabel13.setFont(new java.awt.Font("Stencil Std", 1, 24)); // NOI18N
        jLabel13.setText("Pin Code:");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(680, 680, 126, 25);
        getContentPane().add(jLabel14);
        jLabel14.setBounds(331, 54, 0, 0);

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/login background.jpg"))); // NOI18N
        getContentPane().add(jLabel15);
        jLabel15.setBounds(0, 0, 1950, 1080);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        try {
            File imgfile = new File(image.getText());
            FileInputStream fis = new FileInputStream(imgfile);

            Class.forName("com.mysql.jdbc.Driver");
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/fashion_store_db", "root", "");
            PreparedStatement pre = conn.prepareStatement("INSERT INTO sign_up VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,CURDATE())");
            pre.setString(1, firstName.getText());
            pre.setString(2, lastName.getText());
            pre.setInt(3,110 );

            pre.setString(4, userName.getText());
            pre.setString(5, password.getText());
            pre.setInt(6, Integer.parseInt(age.getText()));

            pre.setString(7, genderType);
            pre.setString(8, email.getText());
            pre.setString(9, address.getText());

            pre.setString(10, city.getText());
            pre.setInt(11, Integer.parseInt(pinCode.getText()));
            pre.setLong(12, Long.parseLong(phoneNumber.getText()));

            pre.setBinaryStream(13, fis, fis.available());

            pre.executeUpdate();
            pre.close();
            conn.close();
        } catch (IOException | ClassNotFoundException | NumberFormatException | SQLException ex) {
            System.out.println(ex);
        }  
        
        finally{
            JOptionPane.showMessageDialog(this,"Signed up successfully...");
            
            try {
                CustomerShopScreen cs1 = new CustomerShopScreen();
                cs1.setVisible(true);
                this.setVisible(false);
            } catch (Throwable ex) {
                Logger.getLogger(UserSignUpScreen.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButton1MouseClicked

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void imageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imageActionPerformed
        // TODO add your handling code here:
       
        
    }//GEN-LAST:event_imageActionPerformed

    private void maleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleButtonActionPerformed
        // TODO add your handling code here:
        if(maleButton.isSelected())
        {
            femaleButton.setSelected(false);
        }
        else{
            femaleButton.setSelected(true);
        }
    }//GEN-LAST:event_maleButtonActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
 JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Select Photo");
        int returnValue = fileChooser.showOpenDialog(this);
        if(returnValue == fileChooser.APPROVE_OPTION) {
            File photoFile = fileChooser.getSelectedFile();
            image.setText(photoFile.getPath());
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void pinCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pinCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pinCodeActionPerformed

    private void ageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ageActionPerformed

    private void cityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cityActionPerformed

    private void phoneNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneNumberActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserSignUpScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserSignUpScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserSignUpScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserSignUpScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserSignUpScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea address;
    private javax.swing.JTextField age;
    private javax.swing.JTextField city;
    private javax.swing.JTextField email;
    private javax.swing.JRadioButton femaleButton;
    private javax.swing.JTextField firstName;
    private javax.swing.JTextField image;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lastName;
    private javax.swing.JRadioButton maleButton;
    private javax.swing.JTextField password;
    private javax.swing.JTextField phoneNumber;
    private javax.swing.JTextField pinCode;
    private javax.swing.JTextField userName;
    // End of variables declaration//GEN-END:variables

    @Override
    public void itemStateChanged(ItemEvent e) {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        if(maleButton.isSelected())
        {
            genderType = "Male";
        }
        if(femaleButton.isSelected())
        {
            genderType = "Female";
        }
    
    }
}
