/*
 * This is the USER LOGIN screen
 * New user can SIGN UP to view the shopping system.
 */
package projectshopping;

import java.awt.Image;
import java.awt.Toolkit;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;


public class UserScreen extends javax.swing.JFrame {

    CustomerRelatedLogic customer;
    static UserScreen us;
    public static int customerId;
    /**
     * Creates new form UserScreen
     *
     * @throws java.lang.Throwable
     */
    public UserScreen() throws Throwable {
        initComponents();

        this.setSize(1920, 1080);
        customer = new CustomerRelatedLogic();
         this.setTitle("MAD Creationzzz!!!");
        Image icon = Toolkit.getDefaultToolkit().getImage("src/img/i1.jpg");
        this.setIconImage(icon);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Vineta BT", 1, 36)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/generatedtext (1).jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(720, 230, 620, 100);

        jLabel2.setFont(new java.awt.Font("Stencil Std", 1, 36)); // NOI18N
        jLabel2.setText("Enter username :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(577, 400, 380, 50);

        jLabel3.setFont(new java.awt.Font("Stencil Std", 1, 36)); // NOI18N
        jLabel3.setText("Enter password :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(570, 490, 380, 50);

        jTextField1.setFont(new java.awt.Font("Stencil Std", 1, 36)); // NOI18N
        getContentPane().add(jTextField1);
        jTextField1.setBounds(1050, 400, 320, 60);

        jPasswordField1.setFont(new java.awt.Font("Stencil Std", 1, 36)); // NOI18N
        getContentPane().add(jPasswordField1);
        jPasswordField1.setBounds(1050, 490, 320, 60);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/login button 1.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(880, 600, 200, 100);

        jLabel4.setFont(new java.awt.Font("Stencil Std", 3, 36)); // NOI18N
        jLabel4.setText("Do not have an account? Sign up here:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(390, 750, 850, 50);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/sign up button.jpg"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(1260, 730, 200, 90);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/login background.jpg"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 1920, 1070);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(1000, 460, 380, 10);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        int c = 0;
        try {
            // TODO add your handling code here:
            customer.rs = customer.stmt.executeQuery("SELECT   `user_name`, `password`,`customer_id` FROM `sign_up` WHERE 1");
            
            while (customer.rs.next()) {
                if ((customer.rs.getString(1).compareTo(jTextField1.getText()) == 0) && (customer.rs.getString(2).compareTo(jPasswordField1.getText()) == 0)) {
                    c++;
                   customerId = customer.rs.getInt(3);
                   System.out.println(customerId);
                    JOptionPane.showMessageDialog(null, "Login sucessfully", "Success", JOptionPane.INFORMATION_MESSAGE);
                    this.setVisible(false);
                    CustomerShopScreen cs = new CustomerShopScreen();
                    cs.setVisible(true);

                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(UserScreen.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Throwable ex) {
            Logger.getLogger(UserScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (c == 0) {
            JOptionPane.showMessageDialog(null, "Invalid Username or password", "Success", JOptionPane.INFORMATION_MESSAGE);

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        UserSignUpScreen us1 = new UserSignUpScreen();
        us1.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    us = new UserScreen();
                } catch (Throwable ex) {
                    Logger.getLogger(UserScreen.class.getName()).log(Level.SEVERE, null, ex);
                }

                us.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
